//! Structured model → `memoir` LaTeX generation — the deterministic core
//! contract `(document.json, settings.json) -> main.tex`.
//!
//! Pure and side-effect-free: the same inputs always produce byte-identical,
//! human-readable, commented output (verified by golden tests). The preamble is
//! generated entirely from `settings.json`; the body from `document.json`;
//! Raw-LaTeX blocks are emitted verbatim.
//!
//! M2 renders with `memoir`'s default Latin Modern fonts (no `fontspec`);
//! `fontspec` + bundled OTF font selection arrives with the PageSetting
//! inspector in M5. The node-id ↔ `.tex` line-range source map arrives in M4.

pub mod model;
pub mod presets;

use std::fmt::Write;

use model::{
    ChapterStyleKind, Document, Inline, Node, ParagraphStyle, Settings,
};

pub use model::{Document as DocumentModel, Settings as SettingsModel};

/// Generate a complete, compilable `main.tex` from the document + settings.
pub fn generate(doc: &Document, settings: &Settings) -> String {
    let mut tex = String::new();
    write_preamble(&mut tex, settings);
    let _ = writeln!(tex, "\\begin{{document}}\n");
    write_matter(&mut tex, doc);
    let _ = writeln!(tex, "\\end{{document}}");
    tex
}

// ----------------------------------------------------------------- preamble

fn write_preamble(tex: &mut String, s: &Settings) {
    let _ = writeln!(tex, "% Generated by EscapeVelocity — do not hand-edit.");
    let _ = writeln!(tex, "% Edit the document or the PageSetting inspector instead;");
    let _ = writeln!(tex, "% Raw-LaTeX blocks are the exception and pass through verbatim.\n");

    let size = s.body.size_pt.round() as i64;
    let openside = if s.chapter.recto_start { "openright" } else { "openany" };
    let _ = writeln!(tex, "\\documentclass[{size}pt,twoside,{openside}]{{memoir}}\n");

    // Packages
    let _ = writeln!(tex, "\\usepackage{{graphicx}}");
    if s.body.microtype {
        let _ = writeln!(tex, "\\usepackage[protrusion=true,expansion=false]{{microtype}}");
    }
    if s.paragraph.style == ParagraphStyle::Indent && !s.paragraph.suppress_first_indent {
        let _ = writeln!(tex, "\\usepackage{{indentfirst}}");
    }
    let _ = writeln!(tex);

    // Trim & stock
    let bleed_note = if s.bleed { ", + 0.125in bleed" } else { "" };
    let _ = writeln!(
        tex,
        "% --- Trim & stock ({} x {} in{}) ---",
        n(s.trim.width_in),
        n(s.trim.height_in),
        bleed_note
    );
    if s.bleed {
        // KDP bleed: 0.125in on top, bottom, and the outside edge.
        let _ = writeln!(
            tex,
            "\\setstocksize{{{}in}}{{{}in}}",
            n(s.trim.height_in + 0.25),
            n(s.trim.width_in + 0.125)
        );
        let _ = writeln!(
            tex,
            "\\settrimmedsize{{{}in}}{{{}in}}{{*}}",
            n(s.trim.height_in),
            n(s.trim.width_in)
        );
        let _ = writeln!(tex, "\\settrims{{{}in}}{{{}in}}", n(0.125), n(0.125));
    } else {
        let _ = writeln!(
            tex,
            "\\setstocksize{{{}in}}{{{}in}}",
            n(s.trim.height_in),
            n(s.trim.width_in)
        );
        let _ = writeln!(
            tex,
            "\\settrimmedsize{{{}in}}{{{}in}}{{*}}",
            n(s.trim.height_in),
            n(s.trim.width_in)
        );
    }

    // Margins (inside = spine/gutter side; mirrored on verso by twoside)
    let _ = writeln!(
        tex,
        "\\setlrmarginsandblock{{{}in}}{{{}in}}{{*}}",
        n(s.margins.inside_in),
        n(s.margins.outside_in)
    );
    let _ = writeln!(
        tex,
        "\\setulmarginsandblock{{{}in}}{{{}in}}{{*}}",
        n(s.margins.top_in),
        n(s.margins.bottom_in)
    );
    let _ = writeln!(tex, "\\checkandfixthelayout\n");

    // Body type
    let _ = writeln!(tex, "% --- Body type ({}, {}pt) ---", s.body.font, n(s.body.size_pt));
    let linespread = s.body.leading_pt / (1.2 * s.body.size_pt);
    let _ = writeln!(tex, "\\linespread{{{}}}", n(linespread));
    if !s.body.hyphenate {
        let _ = writeln!(tex, "\\hyphenpenalty=10000 \\exhyphenpenalty=10000");
    }
    if !s.body.justify {
        let _ = writeln!(tex, "\\AtBeginDocument{{\\raggedright}}");
    }
    let _ = writeln!(tex);

    // Paragraphs
    let _ = writeln!(tex, "% --- Paragraphs ---");
    match s.paragraph.style {
        ParagraphStyle::Indent => {
            let _ = writeln!(tex, "\\setlength{{\\parindent}}{{1.5em}}");
        }
        ParagraphStyle::Spaced => {
            let _ = writeln!(tex, "\\setlength{{\\parindent}}{{0pt}}");
            let _ = writeln!(tex, "\\nonzeroparskip");
        }
    }
    let p = s.paragraph.widow_orphan_penalty;
    let _ = writeln!(tex, "\\clubpenalty={p} \\widowpenalty={p} \\displaywidowpenalty={p}\n");

    // Chapter openings
    let _ = writeln!(tex, "% --- Chapter openings ---");
    match s.chapter.kind {
        ChapterStyleKind::Plain => {
            let _ = writeln!(tex, "\\chapterstyle{{default}}");
        }
        other => {
            let _ = writeln!(
                tex,
                "\\chapterstyle{{default}} % {:?} chapter style arrives in M5",
                other
            );
        }
    }
    let _ = writeln!(tex);

    // Running heads & folios
    let _ = writeln!(tex, "% --- Running heads & folios ---");
    let _ = writeln!(
        tex,
        "\\pagestyle{{{}}}\n",
        if s.running_heads.enabled { "headings" } else { "plain" }
    );
}

// --------------------------------------------------------------------- body

fn write_matter(tex: &mut String, doc: &Document) {
    if !doc.front_matter.is_empty() {
        let _ = writeln!(tex, "\\frontmatter\n");
        for node in &doc.front_matter {
            write_node(tex, node);
        }
    }
    let _ = writeln!(tex, "\\mainmatter\n");
    for node in &doc.body {
        write_node(tex, node);
    }
    if !doc.back_matter.is_empty() {
        let _ = writeln!(tex, "\\backmatter\n");
        for node in &doc.back_matter {
            write_node(tex, node);
        }
    }
}

fn write_node(tex: &mut String, node: &Node) {
    match node {
        Node::Part { title, children } => {
            let _ = writeln!(tex, "% ===== Part: {} =====", plain_text(title));
            let _ = writeln!(tex, "\\part{{{}}}\n", inlines(title));
            for c in children {
                write_node(tex, c);
            }
        }
        Node::Chapter { title, children } => {
            let _ = writeln!(tex, "% --- Chapter: {} ---", plain_text(title));
            let _ = writeln!(tex, "\\chapter{{{}}}\n", inlines(title));
            for c in children {
                write_node(tex, c);
            }
        }
        Node::Section { title, children } => {
            let _ = writeln!(tex, "\\section{{{}}}\n", inlines(title));
            for c in children {
                write_node(tex, c);
            }
        }
        Node::Paragraph { content } => {
            let _ = writeln!(tex, "{}\n", inlines(content));
        }
        Node::Heading { level, content } => {
            let cmd = match level {
                0..=2 => "section",
                3 => "subsection",
                _ => "subsubsection",
            };
            let _ = writeln!(tex, "\\{cmd}{{{}}}\n", inlines(content));
        }
        Node::BlockQuote { content } => {
            let _ = writeln!(tex, "\\begin{{quotation}}");
            let _ = writeln!(tex, "{}", inlines(content));
            let _ = writeln!(tex, "\\end{{quotation}}\n");
        }
        Node::Verse { lines } => {
            let _ = writeln!(tex, "\\begin{{verse}}");
            let rendered: Vec<String> = lines.iter().map(|l| inlines(l)).collect();
            let _ = writeln!(tex, "{}", rendered.join(" \\\\\n"));
            let _ = writeln!(tex, "\\end{{verse}}\n");
        }
        Node::Figure { src, caption } => {
            let _ = writeln!(tex, "\\begin{{figure}}[htbp]");
            let _ = writeln!(tex, "  \\centering");
            let _ = writeln!(tex, "  \\includegraphics[width=\\linewidth]{{{src}}}");
            if !caption.is_empty() {
                let _ = writeln!(tex, "  \\caption{{{}}}", inlines(caption));
            }
            let _ = writeln!(tex, "\\end{{figure}}\n");
        }
        Node::SceneBreak => {
            let _ = writeln!(tex, "\\begin{{center}}* * *\\end{{center}}\n");
        }
        Node::PullQuote { content } => {
            let _ = writeln!(tex, "\\begin{{quote}}\\itshape");
            let _ = writeln!(tex, "{}", inlines(content));
            let _ = writeln!(tex, "\\end{{quote}}\n");
        }
        Node::RawLatex { code } => {
            let _ = writeln!(tex, "{code}\n");
        }
    }
}

// ------------------------------------------------------------------ inlines

fn inlines(items: &[Inline]) -> String {
    let mut s = String::new();
    for it in items {
        match it {
            Inline::Text { value } => s.push_str(&escape_text(value)),
            Inline::Emphasis { content } => {
                let _ = write!(s, "\\emph{{{}}}", inlines(content));
            }
            Inline::Strong { content } => {
                let _ = write!(s, "\\textbf{{{}}}", inlines(content));
            }
            Inline::SmallCaps { content } => {
                let _ = write!(s, "\\textsc{{{}}}", inlines(content));
            }
            // Print interiors don't hyperlink; render the link text.
            Inline::Link { content, .. } => s.push_str(&inlines(content)),
            Inline::Footnote { content } => {
                let _ = write!(s, "\\footnote{{{}}}", inlines(content));
            }
        }
    }
    s
}

/// Plain (unescaped) text of an inline run, for `%` comments only.
fn plain_text(items: &[Inline]) -> String {
    let mut s = String::new();
    for it in items {
        match it {
            Inline::Text { value } => s.push_str(value),
            Inline::Emphasis { content }
            | Inline::Strong { content }
            | Inline::SmallCaps { content }
            | Inline::Footnote { content }
            | Inline::Link { content, .. } => s.push_str(&plain_text(content)),
        }
    }
    // Comments can't contain newlines.
    s.replace(['\n', '\r'], " ")
}

/// Escape LaTeX-special characters in author text.
fn escape_text(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\textbackslash{}"),
            '{' => out.push_str("\\{"),
            '}' => out.push_str("\\}"),
            '$' => out.push_str("\\$"),
            '&' => out.push_str("\\&"),
            '#' => out.push_str("\\#"),
            '%' => out.push_str("\\%"),
            '_' => out.push_str("\\_"),
            '~' => out.push_str("\\textasciitilde{}"),
            '^' => out.push_str("\\textasciicircum{}"),
            _ => out.push(c),
        }
    }
    out
}

/// Format a number with up to 4 decimals, trailing zeros trimmed — deterministic
/// and tidy (e.g. 9.0 -> "9", 0.875 -> "0.875").
fn n(v: f64) -> String {
    let s = format!("{v:.4}");
    let trimmed = s.trim_end_matches('0').trim_end_matches('.');
    trimmed.to_string()
}
